version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Prebuilding, installing npm dependencies"
      - cd aplicacion
      - npm install
  build:
    commands:
      - echo "Starting the build step"
      - npm run build:test
artifacts:
  name: 'BuildOutput'
  files:
    - '**/*'
  base-directory: 'dist/ambulance'
